inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
